// <auto-generated />
using System;
using Entity_Framework_Task;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity_Framework_Task.Migrations
{
    [DbContext(typeof(CompanyDatabaseContext))]
    partial class CompanyDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity_Framework_Task.Entities.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("projectId")
                        .HasColumnType("int");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("departmentId");

                    b.HasIndex("projectId");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            id = 101,
                            departmentId = 3,
                            name = "named Ali Hassan",
                            projectId = 1,
                            salary = 5000m
                        },
                        new
                        {
                            id = 102,
                            departmentId = 2,
                            name = "Sameer Zaki",
                            projectId = 1,
                            salary = 6200m
                        },
                        new
                        {
                            id = 103,
                            departmentId = 1,
                            name = "Khaled Omar",
                            projectId = 1,
                            salary = 4750m
                        },
                        new
                        {
                            id = 104,
                            departmentId = 4,
                            name = "Karim Ahmed",
                            projectId = 1,
                            salary = 5500m
                        },
                        new
                        {
                            id = 105,
                            departmentId = 3,
                            name = "Youssef Nabil",
                            projectId = 2,
                            salary = 7100m
                        },
                        new
                        {
                            id = 106,
                            departmentId = 2,
                            name = "Loay Samir",
                            projectId = 2,
                            salary = 4900m
                        },
                        new
                        {
                            id = 107,
                            departmentId = 2,
                            name = "Omar Fathy",
                            projectId = 2,
                            salary = 6000m
                        },
                        new
                        {
                            id = 108,
                            departmentId = 2,
                            name = "Wael Magdy",
                            projectId = 2,
                            salary = 5800m
                        },
                        new
                        {
                            id = 109,
                            departmentId = 2,
                            name = "Ahmed Tarek",
                            projectId = 2,
                            salary = 6750m
                        },
                        new
                        {
                            id = 110,
                            departmentId = 2,
                            name = "Sameh Hany,",
                            projectId = 3,
                            salary = 4300m
                        },
                        new
                        {
                            id = 111,
                            departmentId = 3,
                            name = "Mahmoud Said",
                            projectId = 3,
                            salary = 5600m
                        },
                        new
                        {
                            id = 112,
                            departmentId = 2,
                            name = "Waleed Adel",
                            projectId = 4,
                            salary = 6100m
                        },
                        new
                        {
                            id = 113,
                            departmentId = 4,
                            name = "Bassel Hossam",
                            projectId = 4,
                            salary = 5400m
                        },
                        new
                        {
                            id = 114,
                            departmentId = 1,
                            name = "ALi Khalil",
                            projectId = 4,
                            salary = 4850m
                        },
                        new
                        {
                            id = 115,
                            departmentId = 3,
                            name = "Hussein Mostafa",
                            projectId = 4,
                            salary = 6900m
                        });
                });

            modelBuilder.Entity("Entity_Framework_Task.Entities.Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("deadLine")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            deadLine = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2012),
                            name = "CRM"
                        },
                        new
                        {
                            id = 2,
                            deadLine = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2019),
                            name = "HR"
                        },
                        new
                        {
                            id = 3,
                            deadLine = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2019),
                            name = "ERP"
                        },
                        new
                        {
                            id = 4,
                            deadLine = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2016),
                            name = "School Management "
                        });
                });

            modelBuilder.Entity("Entity_Framework_Task.Entities.department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("isNew")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            isNew = true,
                            name = "HR"
                        },
                        new
                        {
                            id = 2,
                            isNew = false,
                            name = "IT"
                        },
                        new
                        {
                            id = 3,
                            isNew = true,
                            name = "Finance"
                        },
                        new
                        {
                            id = 4,
                            isNew = false,
                            name = "Operation"
                        },
                        new
                        {
                            id = 5,
                            isNew = false,
                            name = "Markting"
                        });
                });

            modelBuilder.Entity("Entity_Framework_Task.Entities.Employee", b =>
                {
                    b.HasOne("Entity_Framework_Task.Entities.department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity_Framework_Task.Entities.Project", "Project")
                        .WithMany("Employees")
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Entity_Framework_Task.Entities.Project", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Entity_Framework_Task.Entities.department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
